Fixes Issue#3: Added TestPlan.md
m8ttyB/sux pull request #4
Opened 2017-03-26 16:17 UTC by jeanhl

Added a basic TestPlan.md for the beginnings of a test plan for Some User Experience. TestPlan.md covers our current goals of SUX, a general architecture of the project, testing strategies and future steps to keep in mind as we progress. 

Note: Accidentally named the branch issue_2. Should be issue_3

2017-04-05 16:08 UTC, m8ttyB requested changes
A few small nits and then I think we can merge this.

2017-04-05 16:08 UTC, m8ttyB commented on README.md
> +## License
You can directly add the license to the readme and delete the license doc. Use this string

`This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.`

2017-04-05 16:08 UTC, m8ttyB commented on TestPlan.md
> +Introduction</br>
Instead of line breaks, use markdown syntax.

`###Scope`
`##Testing Strategy`
`* Unit Testing`
`* System and Integration Testing`

2017-04-05 16:08 UTC, m8ttyB commented
/cc @kimberlythegeek can you also offer a review?

2017-04-11 18:59 UTC, kimberlythegeek commented
Hi @jeanhl, I apologize for the delay! 

Thank you for your contributions! You've clearly spent a lot of time on this.

2017-04-11 19:00 UTC, merged